/* eslint-disable */
const lang = require('zero-lang');
const __e = require('../../common/escape');
module.exports = function(data) {
    data = data || {};
    var __t;
    var __p = '';
    return (function() {
        __p += '# svg-icon\n\nthis package is generated by [svg-icon][svg-icon]\n\n[svg-icon]: https://github.com/leungwensen/svg-icon/\n';;
        return __p;
    })();
};