module.exports = [
  { name: 'ant-design'       , prefix: 'ant-'         , repo: 'https://github.com/ant-design/ant-design.git'           },
  { name: 'bootstrap'        , prefix: 'bootstrap-'   , repo: 'https://github.com/twbs/bootstrap.git'                  },
  { name: 'devicons'         , prefix: 'dev-'         , repo: 'https://github.com/vorillaz/devicons.git'               },
  { name: 'elusive-iconfont' , prefix: 'elusive-'     , repo: 'https://github.com/reduxframework/elusive-iconfont.git' },
  { name: 'entypo'           , prefix: 'entypo-'      , repo: 'https://github.com/danielbruce/entypo.git'              },
  { name: 'evil-icons'       , prefix: 'evil-'        , repo: 'https://github.com/outpunk/evil-icons.git'              },
  { name: 'flag-icon'        , prefix: 'flag-'        , repo: 'https://github.com/lipis/flag-icon-css.git'             },
  { name: 'flat-ui'          , prefix: 'flat-'        , repo: 'https://github.com/designmodo/Flat-UI.git'              },
  { name: 'font-awesome'     , prefix: 'awesome-'     , repo: 'https://github.com/FortAwesome/Font-Awesome.git'        },
  { name: 'foundation'       , prefix: 'foundation-'  , repo: 'https://github.com/zurb/foundation-icon-fonts.git'      },
  { name: 'game-icons'       , prefix: 'game-'        , repo: 'https://github.com/game-icons/icons.git'                },
  { name: 'geomicons-open'   , prefix: 'geom-'        , repo: 'https://github.com/jxnblk/geomicons-open.git'           },
  { name: 'icomoon-free'     , prefix: 'icomoon-'     , repo: 'https://github.com/Keyamoon/IcoMoon-Free.git'           },
  { name: 'ionicons'         , prefix: 'ionic-'       , repo: 'https://github.com/driftyco/ionicons.git'               },
  { name: 'logos'            , prefix: 'logos-'       , repo: 'https://github.com/gilbarbara/logos.git'                },
  { name: 'maki'             , prefix: 'maki-'        , repo: 'https://github.com/mapbox/maki.git'                     },
  { name: 'map-icons'        , prefix: 'map-'         , repo: 'https://github.com/scottdejonge/map-icons.git'          },
  { name: 'material-design'  , prefix: 'material-'    , repo: 'https://github.com/google/material-design-icons.git'    },
  { name: 'metro-ui-css'     , prefix: 'metro-'       , repo: 'https://github.com/olton/Metro-UI-CSS.git'              },
  { name: 'mfglabs-iconset'  , prefix: 'mfglabs-'     , repo: 'https://github.com/MfgLabs/mfglabs-iconset.git'         },
  { name: 'octicons'         , prefix: 'oct-'         , repo: 'https://github.com/primer/octicons.git'                 },
  { name: 'open-iconic'      , prefix: 'open-'        , repo: 'https://github.com/iconic/open-iconic.git'              },
  { name: 'payment-font'     , prefix: 'payment-'     , repo: 'https://github.com/vendocrat/PaymentFont.git'           },
  { name: 'payment-webfont'  , prefix: 'payment-web-' , repo: 'https://github.com/orlandotm/payment-webfont.git'       },
  { name: 'simple-icons'     , prefix: 'simple-'      , repo: 'https://github.com/danleech/simple-icons.git'           },
  { name: 'subway'           , prefix: 'subway-'      , repo: 'https://github.com/mariuszostrowski/subway.git'         },
  { name: 'typicons'         , prefix: 'typcn-'       , repo: 'https://github.com/stephenhutchings/typicons.font.git'  },
  { name: 'weather-icons'    , prefix: 'weather-'     , repo: 'https://github.com/erikflowers/weather-icons.git'       },
  { name: 'windows-icons'    , prefix: 'windows-'     , repo: 'https://github.com/Templarian/WindowsIcons.git'         },
  { name: 'zocial'           , prefix: 'zocial-'      , repo: 'https://github.com/smcllns/css-social-buttons.git'      },
];

